syntax = "proto3";

package inventory;

option go_package = "github.com/ighfarhasbi/grpc_service/proto/inventory;inventorypb";

// Inventory Service 
service InventoryService {
  // Cek apakah stok produk tersedia
  rpc CheckStock(CheckStockRequest) returns (CheckStockResponse) {}
  // Reservasi stok untuk sebuah order (hold sementara)
  rpc ReserveStock(ReserveStockRequest) returns (ReserveStockResponse) {}
  // Lepaskan stok yang sudah di-reserve (rollback jika order gagal)
  rpc ReleaseStock(ReleaseStockRequest) returns (ReleaseStockResponse) {}
  // get product by id (untuk di call oleh order service, untuk mendapatkan harga produk)
  rpc GetProduct(GetProductRequest) returns (GetProductResponse) {}
}

// Message Definitions
message CheckStockRequest {
  string product_id = 2;     // UUID produk
  int32 quantity = 3;        // qty yang diminta
}

message CheckStockResponse {
  bool available = 1;        // true jika stok cukup
  int32 available_qty = 2;   // jumlah stok yang tersedia sekarang
  ErrorInfo error = 3;       // isi kalau ada error
}

message ReserveStockRequest {
  string order_id = 2;
  string product_id = 3;
  int32 quantity = 4;
}

message ReserveStockResponse {
  bool success = 1;
  string reservation_id = 2;   // UUID reservation
  ErrorInfo error = 3;
}

message ReleaseStockRequest {
  string reservation_id = 2;   // id reservation yang mau dilepas
}

message ReleaseStockResponse {
  bool success = 1;
  ErrorInfo error = 2;
}

message GetProductRequest {
  string product_id = 1;       // UUID produk
}

message GetProductResponse {
  string product_id = 1;
  string sku = 2;
  string name = 3;
  double price = 4;
  int32 stock = 5;
  ErrorInfo error = 6;
}

// Error Message
message ErrorInfo {
  string code = 1;       // OUT_OF_STOCK, RESERVATION_NOT_FOUND
  string message = 2;    
}
