// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// InventoryRepository is an autogenerated mock type for the InventoryRepository type
type InventoryRepository struct {
	mock.Mock
}

// CancelReservation provides a mock function with given fields: ctx, tx, reservationID
func (_m *InventoryRepository) CancelReservation(ctx context.Context, tx *sql.Tx, reservationID string) error {
	ret := _m.Called(ctx, tx, reservationID)

	if len(ret) == 0 {
		panic("no return value specified for CancelReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string) error); ok {
		r0 = rf(ctx, tx, reservationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateReservation provides a mock function with given fields: ctx, tx, reservationId, orderID, productID, qty
func (_m *InventoryRepository) CreateReservation(ctx context.Context, tx *sql.Tx, reservationId string, orderID string, productID string, qty int) error {
	ret := _m.Called(ctx, tx, reservationId, orderID, productID, qty)

	if len(ret) == 0 {
		panic("no return value specified for CreateReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string, string, string, int) error); ok {
		r0 = rf(ctx, tx, reservationId, orderID, productID, qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProduct provides a mock function with given fields: ctx, productID
func (_m *InventoryRepository) GetProduct(ctx context.Context, productID string) (string, string, float64, int, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 string
	var r1 string
	var r2 float64
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, float64, int, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) float64); ok {
		r2 = rf(ctx, productID)
	} else {
		r2 = ret.Get(2).(float64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string) int); ok {
		r3 = rf(ctx, productID)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(context.Context, string) error); ok {
		r4 = rf(ctx, productID)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// GetReservation provides a mock function with given fields: ctx, reservationID
func (_m *InventoryRepository) GetReservation(ctx context.Context, reservationID string) (string, int, error) {
	ret := _m.Called(ctx, reservationID)

	if len(ret) == 0 {
		panic("no return value specified for GetReservation")
	}

	var r0 string
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, int, error)); ok {
		return rf(ctx, reservationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, reservationID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = rf(ctx, reservationID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, reservationID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetStock provides a mock function with given fields: ctx, productID
func (_m *InventoryRepository) GetStock(ctx context.Context, productID string) (int, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetStock")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStock provides a mock function with given fields: ctx, tx, productID, delta
func (_m *InventoryRepository) UpdateStock(ctx context.Context, tx *sql.Tx, productID string, delta int) error {
	ret := _m.Called(ctx, tx, productID, delta)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string, int) error); ok {
		r0 = rf(ctx, tx, productID, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *InventoryRepository) WithTx(ctx context.Context, fn func(*sql.Tx) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(*sql.Tx) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInventoryRepository creates a new instance of InventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryRepository {
	mock := &InventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
