syntax = "proto3";

package order;

option go_package = "github.com/ighfarhasbi/grpc_service/proto/order;orderpb";

// Order Service
service OrderService {
    rpc CreateOrder(CreateOrderRequest) returns (CreateOrderResponse) {}
    rpc GetOrder(GetOrderRequest) returns (GetOrderResponse) {}
    rpc CancelOrder(CancelOrderRequest) returns (CancelOrderResponse) {}
}

message CreateOrderRequest {
    string user_id = 1;               
    repeated OrderItem items = 2;     
}

message OrderItem {
    string product_id = 1;           
    int32 quantity = 2;               
}

message CreateOrderResponse {
    string order_id = 1;              
    bool success = 2;                
    ErrorInfo error = 3;              
}

message GetOrderRequest {
    string order_id = 1;              
}

message GetOrderResponse {
    string order_id = 1;
    string user_id = 2;
    repeated OrderItem items = 3;
    string status = 4;                
    ErrorInfo error = 5;              
}

message CancelOrderRequest {
    string order_id = 1;              
}

message CancelOrderResponse {
    bool success = 1;                
    ErrorInfo error = 2;              
}

// Error Message
message ErrorInfo {
    string code = 1;                  
    string message = 2;
}